"""add menu category table

Revision ID: 069dd2d81449
Revises: a9351040cbbc
Create Date: 2024-11-16 17:50:13.461639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '069dd2d81449'
down_revision = 'a9351040cbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_category',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('menu_id'),
    sa.UniqueConstraint('menu_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_category')
    # ### end Alembic commands ###
